#!/usr/bin/env bash

_ssh_sshd_config_contents=$( cat <<-LINES
aaa
aaa

LINES
)
    
_no_password_sshd_config_contents=$( cat <<-LINES

bbb
bbb

LINES
)

_ssh_sshd_config_contents="$_ssh_sshd_config_contents $_no_password_sshd_config_contents"

echo "$_ssh_sshd_config_contents"
